name: Corne VIAL Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Setup and Build
      continue-on-error: true
      run: |
        export QMK_HOME='~/qmk_firmware'
        pip install milc
        python3 -m pip install --user qmk
        qmk setup -y
        ls ~/qmk_firmware
        cp -r ~/work/qmk-config/qmk-config/keyboards ~/qmk_firmware/
        make crkbd:custom_vial
